simplesocial/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    path("login/", views.CustomLoginView.as_view(),name='login'),
    path("logout/", views.CustomLogoutView.as_view(), name="logout"),
    path("signup/", views.SignUp.as_view(), name="signup"),
]

simplesocial/posts/urls.py
from django.urls import path,re_path

from . import views

app_name='posts'

urlpatterns = [
    path("", views.PostList.as_view(), name="all"),
    path("new/", views.CreatePost.as_view(), name="create"),
    re_path(r"by/(?P<username>[-\w]+)/$",views.UserPosts.as_view(),name="for_user"),
    re_path(r"by/(?P<username>[-\w]+)/(?P<pk>\d+)/$",views.PostDetail.as_view(),name="single"),
    re_path(r"delete/(?P<pk>\d+)/$",views.DeletePost.as_view(),name="delete"),
]

simplesocial/simplesocial/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views 

urlpatterns = [
    path('', views.HomePage.as_view(), name="home"),
    path('test/', views.TestPage.as_view(), name="test"),
    path("thanks/", views.ThanksPage.as_view(), name="thanks"),
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("posts/", include("posts.urls", namespace="posts")),
    path("groups/",include("groups.urls", namespace="groups")),
]

simplesocial/templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <meta charset="utf-8">
    <title>Star Social</title>
    
    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
 
    <!-- Latest compiled and minified CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <!-- Medium Editor CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/medium-editor@latest/dist/css/medium-editor.min.css"
        integrity="sha384-DxXzQmDijEuX+QX3C1kT4WPUUKi2jG1h+OaUMOmu1KdCpJ5tfP9DT0aaJGo0cXAE" crossorigin="anonymous">

    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'simplesocial/css/master.css'%}">

    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Montserrat&family=Russo+One&display=swap" rel="stylesheet">

    <!-- Medium Editor JavaScript -->
    <script src="https://cdn.jsdelivr.net/npm/medium-editor@latest/dist/js/medium-editor.min.js"
        integrity="sha384-tXPtjA8pWIlD/CwJhlZghLprc6nNkbRVbdbWQNkYVcdPQ9KrI6/ntGeXhIFtYQ/4" crossorigin="anonymous"></script>

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/5.3.1/js/bootstrap.bundle.min.js"
        integrity="sha384-OySdoPqpspDP5p6i7T0P1MsE2XtyWvOsKofNxI8uMwsZDk4RUJ4aSD/7ONg9ZZU2" crossorigin="anonymous"></script>

  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'home' %}">Star Social</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav ms-auto">
            {% if user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'posts:create' %}">Post</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'groups:all' %}">Groups</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'groups:create' %}">Create Group</a>
              </li>
              <li class="nav-item">
                <form method="post" action="{% url 'accounts:logout' %}">
                  {% csrf_token %}
                  <button type="submit" class="btn btn-simple">Log out</button>
                </form>
              </li>
              
            
            {% else %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'groups:all' %}">Groups</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:login' %}">Log in</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:signup' %}">Sign up</a>
              </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>

    <div class="container mycontent">
      {% block content %}
      {% endblock %}
    </div>

    <canvas id="canvas"></canvas>
  </body>
  <script src="{% static 'simplesocial/js/master.js'%}" type="text/javascript" ></script>
</html>

simplesocial/templates/index.html
{% extends "base.html" %}
{% block content %}

    <h1>Welcome to Star Social!</h1>
    <h2>The best community for all things on outer space!</h2>
    <h2>Login or Sign-up for free to get started!</h2>


{% endblock %}

simplesocial/templates/test.html
{% extends "base.html" %}
{% block content %}
<div class="container">
    <h1>You are now logged in!</h1>
    <h2><a href="{% url 'groups:all'%}">Go to Groups</a></h2>


</div>

{% endblock %}

simplesocial/templates/thanks.html
{% extends "base.html" %}
{% block content %}
<h1>Thanks for visiting! Come back soon!</h1>

{% endblock %}